# Generated by Django 5.2.17 on 2026-09-05 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_aievaluation_humanevaluation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='application',
            new_name='application_challen_7170a3_idx',
            old_name='evaluations_app_challeng_7d31f3_idx',
        ),
        migrations.RenameIndex(
            model_name='application',
            new_name='application_startup_f504ab_idx',
            old_name='evaluations_app_startup_3555ea_idx',
        ),
        migrations.RenameIndex(
            model_name='humanevaluation',
            new_name='human_evalu_applica_e4de38_idx',
            old_name='human_eval_application_created_idx',
        ),
        migrations.RenameIndex(
            model_name='humanevaluation',
            new_name='human_evalu_evaluat_8aeef8_idx',
            old_name='human_eval_evaluator_created_idx',
        ),
    ]
