import uuid

from django.conf import settings
from django.db import models
from pgvector.django import HnswIndex, VectorField


class EvidenceType(models.TextChoices):
    CERTIFICATION = "CERTIFICATION", "Certification"
    GOVERNMENT_PILOT = "GOVERNMENT_PILOT", "Government Pilot"
    DEPLOYMENT = "DEPLOYMENT", "Deployment"
    CASE_STUDY = "CASE_STUDY", "Case Study"
    AWARD = "AWARD", "Award"
    PATENT = "PATENT", "Patent"
    OTHER = "OTHER", "Other"


class Startup(models.Model):
    """
    The Startup Passport (spec section 9-10): a reusable, evidence-backed
    startup identity used for semantic matching (Startup Radar), evaluation,
    pilots, and the Trust Graph.

    This is distinct from `accounts.StartupProfile`, which is the
    lightweight identity captured at registration. A Startup Passport is
    auto-created and seeded from that profile (see signals.py) the moment a
    STARTUP user registers, then evolves independently as the startup adds
    evidence, technologies, and pilot history.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="startup_passport"
    )

    company_name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    website = models.URLField(blank=True)
    industry = models.CharField(max_length=255, blank=True)
    technologies = models.JSONField(default=list, blank=True)
    founded_year = models.PositiveIntegerField(null=True, blank=True)
    team_size = models.PositiveIntegerField(null=True, blank=True)
    location = models.CharField(max_length=255, blank=True)

    # Semantic capability embedding for Startup Radar (pgvector similarity
    # search). Generated by intelligence.embeddings from company_name +
    # description + industry + technologies. System-managed; never accepted
    # as direct API input (see serializers.py).
    embedding = VectorField(dimensions=settings.EMBEDDING_DIMENSIONS, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "startups"
        ordering = ["-created_at"]
        indexes = [
            HnswIndex(
                name="startup_embedding_hnsw",
                fields=["embedding"],
                m=16,
                ef_construction=64,
                opclasses=["vector_cosine_ops"],
            ),
        ]

    def __str__(self):
        return self.company_name

    @property
    def pilot_count(self):
        return self.evidence.filter(evidence_type=EvidenceType.GOVERNMENT_PILOT).count()

    @property
    def deployment_count(self):
        return self.evidence.filter(evidence_type=EvidenceType.DEPLOYMENT).count()

    @property
    def verified_evidence_count(self):
        return self.evidence.filter(verified=True).count()


class StartupEvidence(models.Model):
    """
    Evidence backing a startup's claims (spec section 10, 26): a claim like
    "completed 4 government pilots" should resolve to concrete,
    independently verifiable evidence records.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    startup = models.ForeignKey(Startup, on_delete=models.CASCADE, related_name="evidence")

    evidence_type = models.CharField(max_length=30, choices=EvidenceType.choices)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    document = models.FileField(upload_to="startup_evidence/", null=True, blank=True)
    external_url = models.URLField(blank=True)

    verified = models.BooleanField(default=False)
    verified_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="verified_startup_evidence",
    )
    verified_at = models.DateTimeField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "startup_evidence"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.title} ({self.startup.company_name})"
