# Generated by Django 6.1.1 on 2026-09-05 00:45

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Ensures `CREATE EXTENSION IF NOT EXISTS vector;` runs automatically
        # on any fresh database — no manual psql step required for setup.
        VectorExtension(),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup_passport', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'startups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StartupEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('CERTIFICATION', 'Certification'), ('GOVERNMENT_PILOT', 'Government Pilot'), ('DEPLOYMENT', 'Deployment'), ('CASE_STUDY', 'Case Study'), ('AWARD', 'Award'), ('PATENT', 'Patent'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='startup_evidence/')),
                ('external_url', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='startups.startup')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_startup_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'startup_evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='startup',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='startup_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
