# Generated by Django 5.2.17 on 2026-09-05 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0002_phase8_outcomes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kpi',
            new_name='pilot_kpis_pilot_i_efd09e_idx',
            old_name='pilot_kpis_pilot_i_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='milestone',
            new_name='pilot_miles_pilot_i_962d4e_idx',
            old_name='pilot_miles_pilot_s_2b7d91_idx',
        ),
        migrations.RenameIndex(
            model_name='milestone',
            new_name='pilot_miles_due_dat_2ce3f5_idx',
            old_name='pilot_miles_due_dat_48fbb2_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='pilot_payme_status_825062_idx',
            old_name='pilot_paym_status_7ee9ea_idx',
        ),
        migrations.RenameIndex(
            model_name='pilot',
            new_name='pilots_created_92061f_idx',
            old_name='pilots_created_bf2e6b_idx',
        ),
        migrations.RenameIndex(
            model_name='pilot',
            new_name='pilots_startup_fe6a45_idx',
            old_name='pilots_startup_9c51cc_idx',
        ),
        migrations.RenameIndex(
            model_name='pilotevidence',
            new_name='pilot_evide_pilot_i_3639da_idx',
            old_name='pilot_ev_pilot_m_4f5dd1_idx',
        ),
        migrations.RenameIndex(
            model_name='pilotevidence',
            new_name='pilot_evide_verifie_c5659f_idx',
            old_name='pilot_ev_verified_3a4dd6_idx',
        ),
        migrations.RenameIndex(
            model_name='riskflag',
            new_name='pilot_risk__pilot_i_431b73_idx',
            old_name='pilot_risks_pilot_s_4d5e6f_idx',
        ),
    ]
