import uuid

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from pgvector.django import HnswIndex, VectorField


class ChallengeStatus(models.TextChoices):
    DRAFT = "DRAFT", "Draft"
    OPEN = "OPEN", "Open"
    EVALUATION = "EVALUATION", "Evaluation"
    PILOT = "PILOT", "Pilot"
    COMPLETED = "COMPLETED", "Completed"
    CLOSED = "CLOSED", "Closed"


# Only these transitions are allowed through the API. Keeping the lifecycle
# explicit prevents clients from jumping directly from DRAFT to COMPLETED,
# for example.
ALLOWED_STATUS_TRANSITIONS = {
    ChallengeStatus.DRAFT: {ChallengeStatus.OPEN, ChallengeStatus.CLOSED},
    ChallengeStatus.OPEN: {ChallengeStatus.EVALUATION, ChallengeStatus.CLOSED},
    ChallengeStatus.EVALUATION: {ChallengeStatus.PILOT, ChallengeStatus.CLOSED},
    ChallengeStatus.PILOT: {ChallengeStatus.COMPLETED, ChallengeStatus.CLOSED},
    ChallengeStatus.COMPLETED: set(),
    ChallengeStatus.CLOSED: set(),
}


class Challenge(models.Model):
    """A government-defined problem that startups can apply to solve."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="challenges",
    )

    title = models.CharField(max_length=255)
    problem_statement = models.TextField()
    desired_outcome = models.TextField()
    requirements = models.JSONField(default=list, blank=True)
    constraints = models.JSONField(default=list, blank=True)

    budget = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    application_deadline = models.DateField(null=True, blank=True)

    # Semantic representation used by Startup Radar. Generated by the
    # intelligence embedding service; never accepted as direct API input.
    embedding = VectorField(dimensions=settings.EMBEDDING_DIMENSIONS, null=True, blank=True)

    status = models.CharField(
        max_length=20,
        choices=ChallengeStatus.choices,
        default=ChallengeStatus.DRAFT,
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "challenges"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["created_by", "status"]),
            models.Index(fields=["status", "application_deadline"]),
            HnswIndex(
                name="challenge_embedding_hnsw",
                fields=["embedding"],
                m=16,
                ef_construction=64,
                opclasses=["vector_cosine_ops"],
            ),
        ]

    def __str__(self):
        return self.title

    def clean(self):
        errors = {}

        if self.start_date and self.application_deadline:
            if self.application_deadline > self.start_date:
                errors["application_deadline"] = (
                    "Application deadline cannot be after the challenge start date."
                )

        if self.budget is not None and self.budget < 0:
            errors["budget"] = "Budget cannot be negative."

        if errors:
            raise ValidationError(errors)

    def can_transition_to(self, new_status):
        return new_status in ALLOWED_STATUS_TRANSITIONS.get(self.status, set())

    def transition_to(self, new_status):
        if new_status == self.status:
            raise ValidationError({"status": "Challenge is already in this status."})

        if not self.can_transition_to(new_status):
            raise ValidationError(
                {
                    "status": (
                        f"Cannot transition challenge from {self.status} to {new_status}."
                    )
                }
            )

        self.status = new_status
