# Generated by Django 5.2.17 on 2026-09-05 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_embedding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='challenge',
            new_name='challenges_created_739886_idx',
            old_name='challenges_created_b9c7c7_idx',
        ),
        migrations.RenameIndex(
            model_name='challenge',
            new_name='challenges_status_2b0ea0_idx',
            old_name='challenges_status_0e9d22_idx',
        ),
    ]
